name: publish as latest
on:
  # publish on pushes to the main branch (image tagged as "latest")
  # https://ocm.software/ocm/pkgs/container/ocm
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
      - 'resources/**'

jobs:

  ocm-cli-latest:
    name: ocm-cli build latest
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
    - name: Self Hosted Runner Post Job Cleanup Action
      uses: TooMuch4U/actions-clean@v2.2
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.OCMBOT_APP_ID }}
        private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.generate_token.outputs.token }}
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: '${{ github.workspace }}/go.mod'
        check-latest: false
    - name: Run GoReleaser build
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: 2.2.0
        args: release --clean --timeout 60m --snapshot --verbose --skip=validate --config=.github/config/latest.yml
      env:
        GITHUBORG: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Enable gh-CLI
      uses: actions4gh/setup-gh@v1.0.2
      id: setup-gh
      with:
        token: ${{ steps.generate_token.outputs.token }}
    - name: Update release assets
      run: |
        RELEASE_ID=$(gh api -X GET -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/hilmarf/ocm/releases/tags/v0.9.0 | jq -r .id)
        gh api -X DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/hilmarf/ocm/releases/$RELEASE_ID
        #gh api -X PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/hilmarf/ocm/releases/assets/189300480 -f "name=dist/ocm-latest-linux-amd64.tar.gz"
    - name: Create Release
      id: create_release
      uses: Hs1r1us/Release-AIO@v2.0.0
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        tag_name: v0.9.0
        release_name: latest
        asset_files: ./dist/
        body: |
          holds always the latest ocm-cli binaries
        draft: false
        prerelease: true
