name: Markdown

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'

permissions:
  contents: read

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Lint Markdown
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Markdown Linting
        uses: nosborn/github-action-markdown-cli@508d6cefd8f0cc99eab5d2d4685b1d5f470042c1 # v3.5.0
        with:
          files: .
          dot: true
          config_file: .github/config/markdownlint.yml
          ignore_path: .github/config/markdownignore
  verify-links:
    name: Verify links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Markdown verify links
        uses: tcort/github-action-markdown-link-check@f3d33029dca1c4a24b87e2df648f9f4604ef6533 # v1.1.1
        with:
          use-quiet-mode: yes
          use-verbose-mode: no
          config-file: .github/config/markdown-link-check.json
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@336d2b4c911d9e582a8e7aa1143f0e862daefbc0 # 0.53.0
        with:
          config_path: .github/config/spellcheck.yml
          task_name: Markdown

